### ISSUE TITLE
Alertas en "Clientes registrados"

### ISSUE THREAD

**Issue by merchanf** [davidcalle9430/SIDIC#33]
Cuando se da clic a una de las filas en la vista de "Clientes registrados", se abre el formulario pero se abren al rededor de unos 5 o 6 alertas con la siguiente info: 
![issue_clientesregistrados](https://cloud.githubusercontent.com/assets/9278608/12803879/fc009906-cabb-11e5-8964-887316cad910.png)

**Comment by merchanf** [comment]
Hay otro alert en la vista "ajustar candtidad secuencial"

**Comment by davidfcalle** [comment]
Se borró del getForObject los alerts
